CREATE TABLE LIBRO (
    CODIGO SERIAL PRIMARY KEY,
    Titulo VARCHAR(50) NOT NULL,
    Autor VARCHAR(50) NOT NULL,
    Fecha_Publicacion DATE,
    Genero_id INTEGER,
    Seccion_id INTEGER,
    Disponibilidad BOOLEAN
);

CREATE TABLE PRESTAMO(
    ID_PRESTAMO SERIAL PRIMARY KEY,
    Visitante_id INTEGER,
    Libro_id INTEGER,
    Fecha_Prestamo DATE,
    Fecha_Devolucion DATE
);

CREATE TABLE VISITANTE(
    ID_VISITANTE SERIAL PRIMARY KEY,
    Nombre VARCHAR(50) NOT NULL,
    Fecha_Registro DATE
);

CREATE TABLE SECCION(
    ID_SECCION SERIAL PRIMARY KEY,
    Nombre VARCHAR(50) NOT NULL,
    Ubicacion_id INTEGER,
    Tipo_id INTEGER,
    Bibliotecario_id INTEGER
);

CREATE TABLE BIBLIOTECARIO(
    ID_BIBLIOTECARIO SERIAL PRIMARY KEY,
    Nombre VARCHAR(50) NOT NULL,
    Fecha_Contratacion DATE,
    Especialidad_id INTEGER
);

CREATE TABLE UBICACION(
    ID_UBICACION SERIAL PRIMARY KEY,
    Nombre VARCHAR(50)
);

CREATE TABLE TIPO(
    ID_TIPO SERIAL PRIMARY KEY,
    Nombre VARCHAR(50) NOT NULL
);

CREATE TABLE ESPECIALIDAD(
    ID_ESPECIALIDAD SERIAL PRIMARY KEY,
    Nombre VARCHAR(50) NOT NULL
);

CREATE TABLE GENERO(
    ID_GENERO SERIAL PRIMARY KEY,
    Nombre VARCHAR(50) NOT NULL
);


-- Relaciones de la tabla LIBRO
ALTER TABLE LIBRO ADD FOREIGN KEY (Genero_id) REFERENCES GENERO(ID_GENERO);
ALTER TABLE LIBRO ADD FOREIGN KEY (Seccion_id) REFERENCES SECCION(ID_SECCION);

-- Relaciones de la tabla PRESTAMO
ALTER TABLE PRESTAMO ADD FOREIGN KEY (Libro_id) REFERENCES LIBRO(CODIGO);
ALTER TABLE PRESTAMO ADD FOREIGN KEY (Visitante_id) REFERENCES VISITANTE(ID_VISITANTE);

-- Relaciones de la tabla SECCION
ALTER TABLE SECCION ADD FOREIGN KEY (Tipo_id) REFERENCES TIPO(ID_TIPO);
ALTER TABLE SECCION ADD FOREIGN KEY (Bibliotecario_id) REFERENCES BIBLIOTECARIO(ID_BIBLIOTECARIO);
ALTER TABLE SECCION ADD FOREIGN KEY (Ubicacion_id) REFERENCES UBICACION(ID_UBICACION);
