-- CREATE USER ADMIN BIBLIOTECA
CREATE USER adminBiblioteca WITH PASSWORD '******';
-- CREATE DB BDDBIBLIOTECA
CREATE DATABASE BDDBIBLIOTECA WITH ENCODING 'UTF8' TEMPLATE template0 OWNER adminzoo;
-- GRANT ROLES TO USER ADMIN BIBLIOTECA
GRANT ALL PRIVILEGES ON DATABASE BDDBIBLIOTECA TO adminBiblioteca;
--- SET CLIENT INSERT IN UTF8 METACHARSET
SET client_encoding = 'UTF8';

